const Products = [{id:0, 
    productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
    img:"https://i.ibb.co/yqnh2cJ/productone.png",
    price:1000,
    day:2,
    hrs:10,
    mins:50,
    state:"Live Auction",
    statebg:"#D20653",
    heartbg:"#fff",
    stroke:2},

    {id:1, 
    productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
    img:"https://i.ibb.co/HXPMdGB/svgviewer-png-output.png",
    price:1000,
    day:2,
    hrs:10,
    mins:50,
    state:"Live Auction",
    statebg:"#D20653",
    heartbg:"#fff",
    stroke:2},

    {id:2, 
    productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
    img:"https://i.ibb.co/xsS4CsM/svgviewer-png-output.png",
    price:1000,
    day:2,
    hrs:10,
    mins:50,
    state:"Hot Sale",
    statebg:"#FF951D",
    heartbg:"#D20653",
    stroke:0},

    {id:3, 
    productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
    img:"https://i.ibb.co/whTpm8w/svgviewer-png-output.png",
    price:1000,
    day:2,
    hrs:10,
    mins:50,
    state:"Live Auction",
    statebg:"#D20653",
    heartbg:"#fff",
    stroke:2},

    {id:4, 
    productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
    img:"https://i.ibb.co/BCg153n/svgviewer-png-output.png",
    price:1000,
    day:2,
    hrs:10,
    mins:50,
    state:"Live Auction",
    statebg:"#D20653",
    heartbg:"#fff",
    stroke:2},

    {id:5, 
        productName:"Six-Piece Clothing Set (Blouse - Pants - Hat And ...",
        img:"https://i.ibb.co/HXPMdGB/svgviewer-png-output.png",
        price:1000,
        day:2,
        hrs:10,
        mins:50,
        state:"Live Auction",
        statebg:"#D20653",
        heartbg:"#fff",
        stroke:2},
    ];

module.exports = {Products}